[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.16.0" }

[context.dev]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.16.0" }