[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.16.0" }

[context.dev]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.16.0" }


[[redirects]]
  from = "/covers"
  to = "https://google.com"
  status = 200

[[redirects]]
  from = "/jquide"
  to = "https://instagram.com/thejguide"
  status = 200

[[redirects]]
  from = "/cover-contest/apply"
  to = "https://airtable.com/shrlZAwd5KCgTpssT"
  status = 200